# Site settings
title: Export Layers
description: "GIMP 2.8/2.10 plug-in that exports layers as separate images"
baseurl: "/gimp-export-layers"
url: "https://kamilburda.github.io"
repository: "kamilburda/gimp-export-layers"
github_username: "{% include-config 'AUTHOR_NAME' %}"
copyright_years: "{% include-config 'COPYRIGHT_YEARS' %}"

plugin_name: "{% include-config 'PLUGIN_NAME' %}"
plugin_version: "{% include-config 'PLUGIN_VERSION' %}"
plugin_version_release_date: "{% include-config 'PLUGIN_VERSION_RELEASE_DATE' %}"
download_zip_suffix: ".zip"
sections_url: "/sections/"
license_remote_url: "blob/main/LICENSE"
license_local_filename: "LICENSE.txt"

plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-seo-tag

# Build settings
markdown: kramdown
is_release_build: false
